name: production_pool
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^7.0.2
  flutter_dotenv: ^5.0.2
  url_strategy: ^0.2.0
  hooks_riverpod: ^2.3.6
  flutter_localization: ^0.1.11
  riverpod_annotation: ^2.1.1
  json_serializable: ^6.7.0
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  riverpod_generator: ^2.2.3
  flutter_hooks: ^0.18.6
  flutter_screenutil: ^5.8.4
  lottie: ^2.4.0
  fl_chart: ^0.63.0
  dio: ^5.2.0
  supabase_flutter: ^1.10.3
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  collection:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/jsons/

