name: production_pool
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^7.0.2
  flutter_dotenv: ^5.0.2
  url_strategy: ^0.2.0
  hooks_riverpod: ^2.3.6
  flutter_localization: ^0.1.11
  riverpod_annotation: ^2.1.1
  json_serializable: ^6.7.0
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  riverpod_generator: ^2.2.3
  flutter_hooks: ^0.18.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  

flutter:

  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

