// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVxakyR_Ipk-Y3NHQuvesxdmNm5D3bycA',
    appId: '1:872023988105:web:b08f0cb00f20f982163358',
    messagingSenderId: '872023988105',
    projectId: 'pool-a2005',
    authDomain: 'pool-a2005.firebaseapp.com',
    storageBucket: 'pool-a2005.appspot.com',
    measurementId: 'G-4NJVQYE2WF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdtVm4vBamj2DITnsVNNXJxZJdJ47oW58',
    appId: '1:872023988105:android:a2b0e326051f4e27163358',
    messagingSenderId: '872023988105',
    projectId: 'pool-a2005',
    storageBucket: 'pool-a2005.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSCixqbzJAsvE2WRJCtFvwD2BSQGi4KQI',
    appId: '1:872023988105:ios:ffca6ba2fd0a8737163358',
    messagingSenderId: '872023988105',
    projectId: 'pool-a2005',
    storageBucket: 'pool-a2005.appspot.com',
    iosClientId: '872023988105-bbehdq10rjef224fu4aeam1l4p0hkfoa.apps.googleusercontent.com',
    iosBundleId: 'com.narwhal.pool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSCixqbzJAsvE2WRJCtFvwD2BSQGi4KQI',
    appId: '1:872023988105:ios:373949246dc58a1f163358',
    messagingSenderId: '872023988105',
    projectId: 'pool-a2005',
    storageBucket: 'pool-a2005.appspot.com',
    iosClientId: '872023988105-ij2raj50gtvfb09l63iq7u6htb2t6j21.apps.googleusercontent.com',
    iosBundleId: 'com.example.productionPool',
  );
}
